export const caseStudies = [
  {
    title: "n8n activation and first workflow",
    format: "Activation strategy · Project deck",
    summary: "Research into the gap between exploring workflow templates and reaching a first live deployment, with a proposed guided learning path and in-canvas assistant.",
    href: "https://assets.nextleap.app/submissions/NLn8n-0c10e538-7621-4a57-a830-14802f8aaff3.pdf",
    linkLabel: "View",
    thumbnail: "/case-studies/n8n-activation.png",
  },
  {
    title: "Gemini UX audit",
    format: "UX audit",
    summary: "A structured review of the Gemini experience using Laws of UX.",
    href: "https://assets.nextleap.app/submissions/GoogleGeminiUXAnalysisLawsofUXEvaluation_LIP-e77f349d-09a7-4276-9d41-f01b5af32a88.pdf-8ebd00ad-d5f8-4f7b-8fb7-27ab17934657.pdf",
    linkLabel: "View",
    thumbnail: "https://assets.nextleap.app/image/eyJidWNrZXQiOiJuZXh0bGVhcC1zdGF0aWMtYXNzZXRzIiwia2V5IjoiaW1hZ2VzL0dvb2dsZUdlbWluaVVYQW5hbHlzaXNMYXdzb2ZVWEV2YWx1YXRpb25fTElQLWU3N2YzNDlkLTA5YTctNDI3Ni05ZDQxLWYwMWI1YWYzMmE4OC5wZGYtYTY1YTIxOTctNjczMS00MjA0LTllYWQtMDE2YjUxNzc0Nzk2LmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NTk3LjMzMzMzMzMzMzMzMzMsImhlaWdodCI6MzM2LCJmaXQiOiJjb3ZlciIsIndpdGhvdXRFbmxhcmdlbWVudCI6dHJ1ZX0sInJvdGF0ZSI6bnVsbH19",
  },
  {
    title: "Gumloop onboarding teardown",
    format: "Product teardown",
    summary: "An examination of the onboarding journey and how users reach value in an AI workflow product.",
    href: "https://assets.nextleap.app/submissions/LIP2-ProductTeardown-9039d7c5-f443-45a6-a2d1-b71986a4474d.pdf2-3e701fb2-6175-4937-9d6a-51fb78ae33a1.pdf",
    linkLabel: "View",
    thumbnail: "https://assets.nextleap.app/image/eyJidWNrZXQiOiJuZXh0bGVhcC1zdGF0aWMtYXNzZXRzIiwia2V5IjoiaW1hZ2VzL0xJUDItUHJvZHVjdFRlYXJkb3duLTkwMzlkN2M1LWY0NDMtNDVhNi1hMmQxLWI3MTk4NmE0NDc0ZC5wZGYtNzJkODY3ZTMtYzg2My00MDVlLTk2YzgtMjMyMjQwYTU0ZTZlLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NTk3LjMzMzMzMzMzMzMzMzMsImhlaWdodCI6MzM2LCJmaXQiOiJjb3ZlciIsIndpdGhvdXRFbmxhcmdlbWVudCI6dHJ1ZX0sInJvdGF0ZSI6bnVsbH19",
  },
  {
    title: "Bumble date-planning assistant",
    format: "Product wireframe",
    summary: "A wireframe exploring an AI-assisted way to turn a match conversation into a plan.",
    href: "https://assets.nextleap.app/submissions/Bumble-68383aa5-2971-450a-8baf-70fb471fd73e.pdf1-eb36fac5-0264-451e-aeef-3f5235cd40c6.pdf",
    linkLabel: "View",
    thumbnail: "https://assets.nextleap.app/image/eyJidWNrZXQiOiJuZXh0bGVhcC1zdGF0aWMtYXNzZXRzIiwia2V5IjoiaW1hZ2VzL0J1bWJsZS02ODM4M2FhNS0yOTcxLTQ1MGEtOGJhZi03MGZiNDcxZmQ3M2UucGRmLTBiMWNlYzQ2LTQ0ZmMtNDkyNS04NjBmLWU5M2QzYTk3Yjg1MS5qcGciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjU5Ny4zMzMzMzMzMzMzMzMzLCJoZWlnaHQiOjMzNiwiZml0IjoiY292ZXIiLCJ3aXRob3V0RW5sYXJnZW1lbnQiOnRydWV9LCJyb3RhdGUiOm51bGx9fQ==",
  },
  {
    title: "FanCode live match community",
    format: "Product exercise",
    summary: "A product exercise exploring community participation around live sports matches.",
    href: "https://assets.nextleap.app/submissions/FanCodePRD-7dc1324b-8f87-4650-8c0a-f4c1f20f069c.pdf",
    linkLabel: "View",
    thumbnail: "https://assets.nextleap.app/image/eyJidWNrZXQiOiJuZXh0bGVhcC1zdGF0aWMtYXNzZXRzIiwia2V5IjoiaW1hZ2VzL0ZhbkNvZGVQcm9kdWN0VGVhcmRvd24tM2Y2OGNlNDUtZGI3NC00NjZjLTg4NmQtZDQ1ZTRmNWY4NjZhLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NTk3LjMzMzMzMzMzMzMzMzMsImhlaWdodCI6MzM2LCJmaXQiOiJjb3ZlciIsIndpdGhvdXRFbmxhcmdlbWVudCI6dHJ1ZX0sInJvdGF0ZSI6bnVsbH19",
  },
  {
    title: "CheQ Product Challenge",
    format: "Product challenge",
    summary: "A product challenge exploring CheQ's user experience and product opportunities.",
    href: "https://assets.nextleap.app/submissions/cheq-99d548ec-3032-4b1a-87c8-ed3f34688b25.pdf",
    linkLabel: "View",
    thumbnail: "https://assets.nextleap.app/image/eyJidWNrZXQiOiJuZXh0bGVhcC1zdGF0aWMtYXNzZXRzIiwia2V5IjoiaW1hZ2VzL1NjcmVlbnNob3QyMDI1LTA5LTA1YXQ3LjE4LjExUE0tNjc0MjhiMDktMGJlYS00NWMwLWFhNzUtZjIxMjQwNmExMjZjLnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NjAwLCJoZWlnaHQiOjMzNiwiZml0IjoiY292ZXIiLCJ3aXRob3V0RW5sYXJnZW1lbnQiOnRydWV9LCJyb3RhdGUiOm51bGx9fQ==",
  },
  {
    title: "ChatGPT mobile voice input",
    format: "Product case study",
    summary: "Exploring how to increase the use of voice input in the ChatGPT mobile app.",
    href: "https://nextleap.app/portfolio/fuzail-kazi",
    linkLabel: "View",
  },
];
