import type { WorkItem, WorkPageContent } from "@/lib/types";

// Maps 1:1 to the `work` array + work/case views in portfolio-final-design.html.
export const workPage: WorkPageContent = {
  beforeLabel: "Before me",
  afterLabel: "After me",
  scope: "scope: owned launch process + exec rhythm for a 40-person org",
  beforeTag: "BEFORE",
  afterTag: "AFTER",
  tapHint: "tap to flip",
  callPrefix: "The call: ",
  caseLinkLabel: "full case study →",
  backLabel: "← Work",
  caseTitleSuffix: " — case study",
  rowLabels: {
    mess: "THE MESS",
    call: "THE CALL",
    system: "THE SYSTEM",
    result: "RESULT",
  },
  slots: ["📄 full deck (PDF viewer)", "🖼 redacted artifact"],
};

export const work: WorkItem[] = [
  {
    slug: "launch-ops",
    title: "Launch ops",
    icon: "rocket",
    before: "3 teams, no shared roadmap, launches slipping 6+ weeks.",
    after: "One roadmap, weekly cadence. Shipped in 5 weeks.",
    call: "Killed status meetings, replaced with one living doc.",
    scope: "owned launch process + exec rhythm for a 40-person org",
    hasCase: true,
    full: false,
    caseStudy: {
      scope: "scope: owned launch process for a 40-person org",
      mess: "Product launches were handled via scattered threads and varying templates. Ownership diffused, deadlines missed, launches slipped 6+ weeks.",
      call: "Killed all status meetings. One living doc, one weekly 20-minute sync, disagreements resolved in comments before the room.",
      system: "async team updates → living doc + 20-min sync → one exec-visible roadmap",
      result:
        "Next launch shipped in 5 weeks end-to-end. The process still runs without me in the room.",
    },
  },
  {
    slug: "exec-reporting",
    title: "Exec reporting",
    icon: "chart",
    before: "Every Friday lost to assembling decks by hand.",
    after: "Automated pipeline. Reporting time down 60%.",
    call: "Built it myself instead of waiting for eng.",
    scope: "owned exec reporting rhythm",
    hasCase: false,
    full: false,
  },
  {
    slug: "ai-tooling",
    title: "AI tooling",
    icon: "sparkles",
    before: "Team drowning in repetitive analysis requests.",
    after: "Internal assistant handles the first pass.",
    call: "Scoped v1 to one workflow — shipped in 2 weeks.",
    scope: "owned internal AI tooling",
    hasCase: false,
    full: false,
  },
  {
    slug: "hiring-loop",
    title: "Hiring loop",
    icon: "people",
    before: "Inconsistent interviews, offer-stage ghosting.",
    after: "Structured loop, scorecards, close rate up.",
    call: "Every interviewer writes before they speak.",
    scope: "owned hiring process",
    hasCase: false,
    full: false,
  },
  {
    slug: "the-thing-i-killed",
    title: "The thing I killed",
    icon: "scissors",
    before: "A beloved project eating 20% of eng with no path to users.",
    after: "Sunset in 3 weeks, capacity moved to the launch above.",
    call: "Wrote the kill memo myself, took the heat.",
    scope: "owned the sunset decision",
    hasCase: false,
    full: true,
  },
];
