import type { WorkItem, WorkPageContent } from "@/lib/types";

export const workPage: WorkPageContent = {
  beforeLabel: "Before",
  afterLabel: "What I did",
  scope: "scope: AI product, developer experience, go-to-market, and product practice",
  beforeTag: "CONTEXT",
  afterTag: "MY WORK",
  tapHint: "tap to explore",
  callPrefix: "The approach: ",
  caseLinkLabel: "open case study →",
  backLabel: "← Work",
  caseTitleSuffix: " · case study",
  rowLabels: {
    mess: "CONTEXT",
    call: "DECISION",
    system: "APPROACH",
    result: "OUTCOME",
  },
  slots: [],
};

export const work: WorkItem[] = [
  {
    slug: "armoriq-product",
    title: "AI product at ArmorIQ",
    icon: "shield",
    before: "Technical products need a clear user problem, a focused direction, and feedback from the people evaluating them.",
    after: "I work across AI product development at ArmorIQ, connecting product decisions with market feedback and the needs of technical users.",
    call: "Keep the product grounded in real developer and customer problems.",
    scope: "AI product work at ArmorIQ",
    category: "ArmorIQ · Product",
    hasCase: false,
    full: false,
  },
  {
    slug: "armor-tools",
    title: "Armor Tools: product to adoption",
    icon: "users",
    before: "A product is not ready for adoption just because it works. Developers need to understand its value and find a clear path to use it.",
    after: "For Armor Tools, I work across product building, developer relations, documentation, content, market feedback, and India go-to-market.",
    call: "Treat documentation, education, and developer feedback as part of the product experience.",
    scope: "Armor Tools is a product within ArmorIQ",
    category: "ArmorIQ · Developer experience and GTM",
    hasCase: false,
    full: false,
  },
  {
    slug: "accelchain-product",
    title: "Product management at AccelChain",
    icon: "rocket",
    before: "A developer platform serving 5,000+ daily users needed a dedicated owner for product direction and developer experience.",
    after: "As sole PM, I owned discovery, prioritization, onboarding improvements, documentation, analytics, and launches across AI and Web3.",
    call: "Use developer feedback and product data together to decide what to improve next.",
    scope: "Product Manager · AccelChain · 2024–2025",
    category: "Professional experience",
    hasCase: true,
    full: false,
    caseStudy: {
      scope: "Sole product manager for a developer platform across AI and Web3",
      mess: "Developers encountered friction during integration and deployment, while the team needed a clearer view of onboarding and activation.",
      call: "Combined developer conversations and usage data to find where the journey was breaking down, then prioritized product, SDK, and documentation improvements.",
      system: "Developer feedback → funnel diagnosis → product and documentation changes → KPI tracking",
      result: "Integration failures decreased by 30%, time to first deployment decreased by 35%, and the AccelChain Marketplace increased project visibility by 40% and became the top sign-up driver within two months.",
    },
  },
  {
    slug: "dapp-world-devrel",
    title: "Developer relations at DApp World",
    icon: "users",
    before: "A developer community was generating useful feedback that needed to reach the product team.",
    after: "I worked with a community of 1,200+ developers, ran workshops and hackathons, and carried recurring feedback into product conversations.",
    call: "Turn developer questions and community activity into useful product insights.",
    scope: "Developer Relations Intern · DApp World · 2023",
    category: "Professional experience",
    hasCase: false,
    full: false,
  },
];
