import type { WorkItem, WorkPageContent } from "@/lib/types";

export const workPage: WorkPageContent = {
  beforeLabel: "Before",
  afterLabel: "What I did",
  scope: "scope: AI product, developer experience, go-to-market, and product practice",
  beforeTag: "CONTEXT",
  afterTag: "MY WORK",
  tapHint: "tap to explore",
  callPrefix: "The approach: ",
  caseLinkLabel: "open case study →",
  backLabel: "← Work",
  caseTitleSuffix: " · case study",
  rowLabels: {
    mess: "CONTEXT",
    call: "DECISION",
    system: "APPROACH",
    result: "OUTCOME",
  },
  slots: [],
};

export const work: WorkItem[] = [
  {
    slug: "armoriq-product",
    title: "AI product at ArmorIQ",
    icon: "shield",
    before: "Technical products need a clear user problem, a focused direction, and feedback from the people evaluating them.",
    after: "I work across AI product development at ArmorIQ, connecting product decisions with market feedback and the needs of technical users.",
    call: "Keep the product grounded in real developer and customer problems.",
    scope: "AI product work at ArmorIQ",
    category: "ArmorIQ · Product",
    hasCase: false,
    full: false,
  },
  {
    slug: "armor-tools",
    title: "Armor Tools: product to adoption",
    icon: "users",
    before: "A product is not ready for adoption just because it works. Developers need to understand its value and find a clear path to use it.",
    after: "For Armor Tools, I work across product building, developer relations, documentation, content, market feedback, and India go-to-market.",
    call: "Treat documentation, education, and developer feedback as part of the product experience.",
    scope: "Armor Tools is a product within ArmorIQ",
    category: "ArmorIQ · Developer experience and GTM",
    hasCase: false,
    full: false,
  },
  {
    slug: "accelchain-product",
    title: "Product management at AccelChain",
    icon: "rocket",
    before: "A developer platform serving 5,000+ daily users needed a dedicated owner for product direction and developer experience.",
    after: "As sole PM, I owned discovery, prioritization, onboarding improvements, documentation, analytics, and launches across AI and Web3.",
    call: "Use developer feedback and product data together to decide what to improve next.",
    scope: "Product Manager · AccelChain · 2024–2025",
    category: "Professional experience",
    hasCase: true,
    full: false,
    caseStudy: {
      scope: "Sole product manager for a developer platform across AI and Web3",
      mess: "Developers encountered friction during integration and deployment, while the team needed a clearer view of onboarding and activation.",
      call: "Combined developer conversations and usage data to find where the journey was breaking down, then prioritized product, SDK, and documentation improvements.",
      system: "Developer feedback → funnel diagnosis → product and documentation changes → KPI tracking",
      result: "Integration failures decreased by 30%, time to first deployment decreased by 35%, and the AccelChain Marketplace increased project visibility by 40% and became the top sign-up driver within two months.",
    },
  },
  {
    slug: "dapp-world-devrel",
    title: "Developer relations at DApp World",
    icon: "users",
    before: "A developer community was generating useful feedback that needed to reach the product team.",
    after: "I worked with a community of 1,200+ developers, ran workshops and hackathons, and carried recurring feedback into product conversations.",
    call: "Turn developer questions and community activity into useful product insights.",
    scope: "Developer Relations Intern · DApp World · 2023",
    category: "Professional experience",
    hasCase: false,
    full: false,
  },
  {
    slug: "n8n-activation",
    title: "Reducing friction to a first n8n workflow",
    icon: "compass",
    before: "New users can explore workflow templates yet still struggle to reach their first live deployment.",
    after: "For a NextLeap PM Fellowship case study, I researched the activation gap and proposed a guided learning path with an in-canvas assistant.",
    call: "Focus the experience on helping a new user achieve a safe first success, not just browse templates.",
    scope: "NextLeap Product Manager Fellowship · product case study",
    category: "Product case study",
    externalUrl: "https://assets.nextleap.app/submissions/NLn8n-0c10e538-7621-4a57-a830-14802f8aaff3.pdf",
    hasCase: false,
    full: false,
  },
  {
    slug: "chatgpt-voice",
    title: "ChatGPT mobile voice input",
    icon: "compass",
    before: "Voice input offers a different way to interact on mobile, and the case study asks how more people might use it.",
    after: "A NextLeap PM Fellowship case study exploring ways to increase voice-input usage in the ChatGPT mobile app.",
    call: "Make the value and ease of voice input clear at the moments it can help most.",
    scope: "NextLeap Product Manager Fellowship · product case study",
    category: "Product case study",
    externalUrl: "https://nextleap.app/portfolio/fuzail-kazi",
    hasCase: false,
    full: false,
  },
  {
    slug: "gemini-ux-audit",
    title: "Gemini UX audit",
    icon: "compass",
    before: "AI products should be evaluated as user experiences, not only as model capabilities.",
    after: "A NextLeap PM Fellowship UX audit using Laws of UX to examine the Gemini experience.",
    call: "Use recognizable UX principles to make qualitative product feedback more structured.",
    scope: "NextLeap Product Manager Fellowship · UX audit",
    category: "Product case study",
    externalUrl: "https://nextleap.app/portfolio/fuzail-kazi",
    hasCase: false,
    full: false,
  },
  {
    slug: "gumloop-onboarding",
    title: "Gumloop onboarding teardown",
    icon: "compass",
    before: "Automation products can feel powerful before a new user knows where to begin.",
    after: "A NextLeap PM Fellowship teardown of Gumloop onboarding, focused on helping users reach value sooner.",
    call: "Trace the journey to first value and identify where guidance could reduce uncertainty.",
    scope: "NextLeap Product Manager Fellowship · product teardown",
    category: "Product case study",
    externalUrl: "https://nextleap.app/portfolio/fuzail-kazi",
    hasCase: false,
    full: false,
  },
  {
    slug: "bumble-assistant",
    title: "Bumble date-planning assistant",
    icon: "compass",
    before: "A promising conversation does not always turn into a concrete plan.",
    after: "A NextLeap PM Fellowship wireframe exploring an AI-assisted date-planning experience.",
    call: "Use AI to help move from conversation to a useful suggestion while keeping people in control.",
    scope: "NextLeap Product Manager Fellowship · wireframe",
    category: "Product case study",
    externalUrl: "https://nextleap.app/portfolio/fuzail-kazi",
    hasCase: false,
    full: false,
  },
  {
    slug: "fancode-community",
    title: "FanCode live match community",
    icon: "users",
    before: "Live match viewing creates a moment to participate, not only follow a score.",
    after: "A NextLeap PM Fellowship product exercise exploring community engagement around live FanCode matches.",
    call: "Connect the live event with lightweight ways for fans to take part together.",
    scope: "NextLeap Product Manager Fellowship · product exercise",
    category: "Product case study",
    externalUrl: "https://nextleap.app/portfolio/fuzail-kazi",
    hasCase: false,
    full: false,
  },
];
