import { readFile } from "node:fs/promises";
import path from "node:path";
import type { EmbeddedChunk, EmbeddingsFile } from "@/lib/types";

export const EMBEDDING_MODEL = "text-embedding-004";
const GEMINI_EMBED_URL = `https://generativelanguage.googleapis.com/v1beta/models/${EMBEDDING_MODEL}:embedContent`;

export type EmbeddingTaskType = "RETRIEVAL_DOCUMENT" | "RETRIEVAL_QUERY";

/** Embed a single text with Gemini. Throws on missing key or API failure. */
export async function embedText(text: string, taskType: EmbeddingTaskType): Promise<number[]> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not set");
  }

  const res = await fetch(GEMINI_EMBED_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-goog-api-key": apiKey,
    },
    body: JSON.stringify({
      content: { parts: [{ text }] },
      taskType,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Gemini embedding failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as { embedding?: { values?: number[] } };
  const values = data.embedding?.values;
  if (!values || values.length === 0) {
    throw new Error("Gemini embedding response contained no values");
  }
  return values;
}

export function cosineSimilarity(a: number[], b: number[]): number {
  if (a.length !== b.length) {
    throw new Error(`Vector length mismatch: ${a.length} vs ${b.length}`);
  }
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

let cachedEmbeddings: EmbeddingsFile | null = null;

/** Load embeddings.json from the project root (generated by `npm run embed`). Cached per process. */
export async function loadEmbeddings(): Promise<EmbeddingsFile> {
  if (cachedEmbeddings) return cachedEmbeddings;
  const filePath = path.join(process.cwd(), "embeddings.json");
  let raw: string;
  try {
    raw = await readFile(filePath, "utf8");
  } catch {
    throw new Error("embeddings.json not found — run `npm run embed` first");
  }
  cachedEmbeddings = JSON.parse(raw) as EmbeddingsFile;
  return cachedEmbeddings;
}

/** Embed the query and return the top-k most similar knowledge chunks. */
export async function retrieve(query: string, k = 4): Promise<EmbeddedChunk[]> {
  const [{ chunks }, queryEmbedding] = await Promise.all([
    loadEmbeddings(),
    embedText(query, "RETRIEVAL_QUERY"),
  ]);

  return chunks
    .map((chunk) => ({ chunk, score: cosineSimilarity(queryEmbedding, chunk.embedding) }))
    .sort((a, b) => b.score - a.score)
    .slice(0, k)
    .map(({ chunk }) => chunk);
}
